# -*- coding: utf-8 -*-
"""(MLAM)_SPRINT_1_CODIGO_PYTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/187cS5VfHGyG3XvbMnMnniO8WxIIFqVjU

# **INTEGRANTES:**
FELIPE PEREIRA RESTIVO - RM: 570712

GABRIEL RODRIGUES ZAPPELLONI - RM: 572060

KENICHI CAIO YAMAMOTO - RM: 569815

MAYKON DE LIMA SILVA - RM: 574022

RODGER COSTA RIOS - RM: 571438
"""

import pandas as pd

df = pd.read_excel('ev_charging_patterns.xlsx')

# 2. Engenharia de Dados
df['Vehicle Age (years)'] = df['Vehicle Age (years)'].round().astype(int)
df['Duração da Recarga (Horas)'] = df['Charging Duration (hours)'].round().astype(int)
df['Faixa de Custo (USD)'] = pd.cut(df['Charging Cost (USD)'], bins=5)
df['Faixa de Energia (kWh)'] = pd.cut(df['Energy Consumed (kWh)'], bins=5)

def gerar_tabela_frequencia(dataframe, nome_coluna, nome_cabecalho_pt):
    freq_absoluta = dataframe[nome_coluna].value_counts()
    freq_relativa = dataframe[nome_coluna].value_counts(normalize=True) * 100

    tabela_final = pd.DataFrame({
        'Frequência Absoluta (Fi)': freq_absoluta,
        'Frequência Relativa (%)': freq_relativa.round(2)
    })

    total_fi = tabela_final['Frequência Absoluta (Fi)'].sum()
    total_pct = tabela_final['Frequência Relativa (%)'].sum()
    tabela_final.loc['TOTAL'] = [total_fi, f"{total_pct:.2f}%"]

    # ALINHAMENTO
    tabela_final = tabela_final.reset_index()
    tabela_final.columns = [nome_cabecalho_pt, 'Frequência Absoluta (Fi)', 'Frequência Relativa (%)']
    return tabela_final.style.hide(axis='index')

print("✓ Ambiente configurado e dados preparados com sucesso!")

print("=== GRUPO A: QUALITATIVAS NOMINAIS ===")
print("\n1. Modelo do Veículo:")
display(gerar_tabela_frequencia(df, 'Vehicle Model', 'Modelo do Veículo'))

print("\n2. Tipo de Usuário:")
display(gerar_tabela_frequencia(df, 'User Type', 'Tipo de Usuário'))

print("=== GRUPO B: QUALITATIVAS ORDINAIS ===")
print("\n3. Tipo de Carregador:")
display(gerar_tabela_frequencia(df, 'Charger Type', 'Tipo de Carregador'))

print("\n4. Período do Dia:")
display(gerar_tabela_frequencia(df, 'Time of Day', 'Período do Dia'))

print("=== GRUPO C: QUANTITATIVAS DISCRETAS ===")
print("\n5. Idade do Veículo (Anos):")
display(gerar_tabela_frequencia(df, 'Vehicle Age (years)', 'Idade do Veículo (Anos)'))

print("\n6. Duração da Recarga (Horas):")
display(gerar_tabela_frequencia(df, 'Duração da Recarga (Horas)', 'Duração da Recarga (Horas)'))

print("=== GRUPO D: QUANTITATIVAS CONTÍNUAS ===")
print("\n7. Custo da Recarga (USD):")
display(gerar_tabela_frequencia(df, 'Faixa de Custo (USD)', 'Faixa de Custo (USD)'))

print("\n8. Energia Consumida (kWh):")
display(gerar_tabela_frequencia(df, 'Faixa de Energia (kWh)', 'Faixa de Energia (kWh)'))