 # -*- coding: utf-8 -*-
"""(MLAM)_SPRINT_2_CODIGO_PYTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fx5b5YsaUzguKt5Uo9p2SnbHpgV4g9dJ

# **INTEGRANTES:**
FELIPE PEREIRA RESTIVO - RM: 570712

GABRIEL RODRIGUES ZAPPELLONI - RM: 572060

KENICHI CAIO YAMAMOTO - RM: 569815

MAYKON DE LIMA SILVA - RM: 574022

RODGER COSTA RIOS - RM: 571438

# **CARREGAMENTO DE DADOS**
"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. CARRGAMENTO DA BASE DE DADOS
df = pd.read_excel('ev_charging_patterns.xlsx')

# 2. ENGENHARIA DE DADOS
df['Vehicle Age (years)'] = df['Vehicle Age (years)'].round().astype(int)
df['Duração da Recarga (Horas)'] = df['Charging Duration (hours)'].round().astype(int)
df['Faixa de Custo (USD)'] = pd.cut(df['Charging Cost (USD)'], bins=5)
df['Faixa de Energia (kWh)'] = pd.cut(df['Energy Consumed (kWh)'], bins=5)

def gerar_tabela_frequencia(dataframe, nome_coluna, nome_cabecalho_pt):
    freq_absoluta = dataframe[nome_coluna].value_counts()
    freq_relativa = dataframe[nome_coluna].value_counts(normalize=True) * 100

    tabela_final = pd.DataFrame({
        'Frequência Absoluta (Fi)': freq_absoluta,
        'Frequência Relativa (%)': freq_relativa.round(2)
    })

    total_fi = tabela_final['Frequência Absoluta (Fi)'].sum()
    total_pct = tabela_final['Frequência Relativa (%)'].sum()
    tabela_final.loc['TOTAL'] = [total_fi, f"{total_pct:.2f}%"]

    # ALINHAMENTO
    tabela_final = tabela_final.reset_index()
    tabela_final.columns = [nome_cabecalho_pt, 'Frequência Absoluta (Fi)', 'Frequência Relativa (%)']
    return tabela_final.style.hide(axis='index')

print("✓ Ambiente configurado e dados preparados com sucesso!")

"""# **GRÁFICOS**

## **GRÁFICO DE SETORES (USER TYPE)**
"""

dados_pizza = df['User Type'].value_counts()

plt.figure(figsize=(6, 6))

plt.pie(
    dados_pizza,
    labels=dados_pizza.index,
    autopct='%1.1f%%',
    colors=['#E8640C', '#1A5FA8', '#4CAF72'],
    startangle=140
)

plt.title('Distribuição de Tipos de Usuário')
plt.legend(title='Tipos de Usuário', loc='upper center', bbox_to_anchor=(1, 1))

plt.show()

"""## **GRÁFICO DE BARRAS (VEHICLE MODEL)**"""

dados_barras = df['Vehicle Model'].value_counts()

plt.figure(figsize=(10, 6))

cores = ['#CC0000', '#003399', '#00A550', '#1C69D4', '#F5C400', '#FF8A5C']

barras = plt.bar(
    dados_barras.index,
    dados_barras,
    color=cores[:len(dados_barras)]
)

plt.title('Distribuição de Recargas por Modelo de Veículo')
plt.xlabel('Modelos de Veículos')
plt.ylabel('Quantidade de Recargas')

plt.legend(barras, dados_barras.index, title='Modelos', loc='upper right')

plt.show()

"""## **HISTOGRAMA (ENERGY CONSUMED(kWh))**"""

plt.figure(figsize=(9, 6))

n, bins, patches = plt.hist(
    df['Energy Consumed (kWh)'],
    bins=12,
    edgecolor='black'
)

for i in range(len(patches)):
    centro_da_barra = (bins[i] + bins[i+1]) / 2
    if centro_da_barra < 30:
        patches[i].set_facecolor('#C6E2F5')
    elif centro_da_barra <= 70:
        patches[i].set_facecolor('#4A90D9')
    else:
        patches[i].set_facecolor('#0D3B6E')

plt.title('Distribuição do Consumo de Energia')
plt.xlabel('Energia Consumida (kWh)')
plt.ylabel('Número de Recargas')

plt.show()

"""## **BOXPLOT (CHARGING DURATION (HOURS))**"""

plt.figure(figsize=(8, 6))

plt.boxplot(
    df['Charging Duration (hours)'],
    patch_artist=True,
    boxprops=dict(facecolor='#4A90D9', color='black'),
    medianprops=dict(color='red', linewidth=2),
    flierprops=dict(marker='o', markerfacecolor='orange', markersize=6)
)

plt.title('Análise de Dispersão da Duração da Recarga')
plt.xlabel('Recargas')
plt.ylabel('Duração (Horas)')

plt.show()

"""# **ESTATÍSTICA DESCRITIVA**"""

colunas_analise = ['Energy Consumed (kWh)', 'Charging Cost (USD)']

estatisticas_completas = {}

for col in colunas_analise:
    estatisticas_completas[col] = {
        # 1. MEDIDAS DE TENDÊNCIAS CENTRAL
        'Média': df[col].mean(),
        'Mediana': df[col].median(),
        'Moda': df[col].mode()[0],

        # 2. MEDIDAS DE DISPERSÃO
        'Mínimo': df[col].min(),
        'Máximo': df[col].max(),
        'Variância': df[col].var(),
        'Desvio Padrão': df[col].std(),
        'Amplitude Total': df[col].max() - df[col].min(),

        # 3. SEPARATRIZES (QUARTIS)
        'Quartil 1 (25%)': df[col].quantile(0.25),
        'Quartil 2 (50%)': df[col].quantile(0.50),
        'Quartil 3 (75%)': df[col].quantile(0.75)
    }

df_estatistica = pd.DataFrame(estatisticas_completas)
print(df_estatistica.round(2))